const fs = require('fs');
const p = 'server/server.js';
let s = fs.readFileSync(p, 'utf8');
s = s.replace('import express from \'express\';', "import express from 'express';\nimport mysql from 'mysql2/promise';");
s = s.replace('const app = express();', 'const app = express();\n\napp.set(\'trust proxy\', 1);');
const si = `\n// ---- Schema auto-setup (idempotent) --------------------------------------\nconst SCHEMA_SQL_PATH = join(__dirname, '..', 'db', 'schema.sql');\nconst POOL_FOR_SCHEMA = mysql.createPool({\n  host: process.env.DB_HOST || (process.env.NODE_ENV === 'production' ? null : 'localhost'),\n  port: Number(process.env.DB_PORT || (process.env.NODE_ENV === 'production' ? null : 3306)),\n  user: process.env.DB_USER || (process.env.NODE_ENV === 'production' ? null : 'root'),\n  password: process.env.DB_PASSWORD ?? (process.env.NODE_ENV === 'production' ? null : ''),\n  database: process.env.DB_NAME || (process.env.NODE_ENV === 'production' ? null : 'cpri'),\n  ssl: process.env.DB_HOST && process.env.DB_HOST.toLowerCase() !== 'localhost'\n    ? { rejectUnauthorized: true }\n    : false,\n  waitForConnections: true,\n  connectionLimit: 1\n});\nasync function loadSchema() {\n  let schema;\n  try {\n    schema = await fs.readFile(SCHEMA_SQL_PATH, 'utf8');\n  } catch (err) {\n    console.error('[schema] could not read ' + SCHEMA_SQL_PATH + ': ' + err.message);\n    return;\n  }\n  await POOL_FOR_SCHEMA.query(schema, { multiStatement: true });\n  console.log('[schema] ready.');\n}\ntry {\n  await loadSchema().catch((err) => {\n    console.error('[schema] initialising database failed:', err.message);\n    console.error('[schema] Check DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME');\n  });\n} catch (err) {\n  console.error('[schema] schema run threw:', err.message);\n}\n`;
s = s.replace('const server = app.listen(PORT, async () => {', si + '\nconst server = app.listen(PORT, async () => {');
fs.writeFileSync(p, s, 'utf8');
console.log('rebuilt');
